import type { Pharmacy } from "../components/PharmacyCard";

// Format UI — compatible avec PharmacyCard
export const mockPharmacies: Pharmacy[] = [
  {
    id: "pha-001",
    name: "Pharmacie du Plateau",
    address: "23 Boulevard de la République, Plateau, Abidjan",
    distanceKm: 0.4,
    open: true,
    rating: 4.8,
    delivery: true,
    pickup: true,
    eta: "15-25 min",
    available: "in-stock",
  },
  {
    id: "pha-002",
    name: "Pharmacie de l'Espérance",
    address: "Cité Sicogi, Bloc B, Yopougon, Abidjan",
    distanceKm: 1.2,
    open: true,
    rating: 4.5,
    delivery: true,
    pickup: true,
    eta: "25-40 min",
    available: "partial",
  },
  {
    id: "pha-003",
    name: "Pharmacie Centrale d'Abidjan",
    address: "Avenue Chardy, Plateau, Abidjan",
    distanceKm: 2.1,
    open: false,
    rating: 4.2,
    delivery: false,
    pickup: true,
    eta: "Ouvre à 8h",
    available: "unknown",
  },
  {
    id: "pha-004",
    name: "Pharmacie Sainte Marie",
    address: "Boulevard Latrille, Cocody, Abidjan",
    distanceKm: 3.4,
    open: true,
    rating: 4.7,
    delivery: true,
    pickup: true,
    eta: "30-45 min",
    available: "in-stock",
  },
];

// Format MCD complet — pour usage API et nouveaux composants
export const mockPharmaciesAPI = [
  {
    id: "pha-001",
    nom: "Pharmacie du Plateau",
    adresse: "23 Boulevard de la République, Plateau, Abidjan",
    email: "plateau.pharmacie@gmail.com",
    telephone: "+225 27 22 45 67 89",
    latitude: 5.3196,
    longitude: -4.0167,
    disponible: true,
    livraisonActive: true,
  },
  {
    id: "pha-002",
    nom: "Pharmacie de l'Espérance",
    adresse: "Cité Sicogi, Bloc B, Yopougon, Abidjan",
    email: "esperance.pharmacie@gmail.com",
    telephone: "+225 27 22 98 76 54",
    latitude: 5.3333,
    longitude: -4.0833,
    disponible: true,
    livraisonActive: true,
  },
  {
    id: "pha-003",
    nom: "Pharmacie Centrale d'Abidjan",
    adresse: "Avenue Chardy, Plateau, Abidjan",
    email: "centrale.pharmacie@gmail.com",
    telephone: "+225 27 22 11 22 33",
    latitude: 5.3220,
    longitude: -4.0120,
    disponible: false,
    livraisonActive: false,
  },
  {
    id: "pha-004",
    nom: "Pharmacie Sainte Marie",
    adresse: "Boulevard Latrille, Cocody, Abidjan",
    email: "+225 27 22 44 55 66",
    telephone: "+225 27 22 44 55 66",
    latitude: 5.3553,
    longitude: -3.9988,
    disponible: true,
    livraisonActive: true,
  },
];
